 /*class Movie {
constructor (movie, studio, rating) {
    this.movie = movie;
    this.studio = studio;
    this.rating = rating;
}
}
var Movie1 = new Movie ('DARBAR', 'LYCA', '4 OUT OF 5');
var Movie2 = new Movie ('DOCTOR', 'S.K', '3 OUT OF 5');
var Movie3 = new Movie ('RRR', 'DVV', '4.5 OUT OF 5');
var Movie4 = new Movie ('PUSHPA', 'M.M', '3 OUT OF 5');
let Movies = [Movie1, Movie2, Movie3, Movie4];
console.log(Movies); */




// write a class to calculate uber price.
 /*class UberPrice {
    constructor(Basefare, Costperminute, Timeinride, Costperkm, Ridingdis, BookingFee) {
      this.Basefare = Basefare;
      this.Costperminute = Costperminute;
      this.Timeinride = Timeinride;
      this.Costperkm = Costperkm;
      this.Ridingdis = Ridingdis;
      this.BookingFee = BookingFee;
    }
    getfare() {
        console.log(`Your fare is : ${this.Basefare + (this.Costperminute * this.Timeinride) + (this.Costperkm * this.Ridingdis) + this.BookingFee }`);
    }
}
let Firstride = new UberPrice (40,7,10,28,15,9);
Firstride.getfare(); */





// Write a “person” class to hold all the details.
  /*class Person {
    constructor (Name, Age, Place, MobileNo){
    this.Name = Name;
    this.Age = Age;
    this.Place = Place;
    this.MobileNo = MobileNo;
}
}
  let Person1 = new Person ('JOHN', '27', 'UNITED STATES', '12345678');
  let Person2 = new Person ('SMITH', '24', 'CALIFORNIA', '89745621512');
let Alldetails = [Person1, Person2];
     console.log(Alldetails);  */

     




// https://github.com/rvsp/typescript-oops/blob/master/Practice/class-circle.md     

  /*class Circle {
constructor (radius, colour){
this.radius = radius;
this.colour = colour;
}
}
let Result = new Circle ('2', 'Red');
console.log(Result); */